
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /v1
    
  error:
    include-stacktrace: on-trace-param

spring:
  application:
    name: internal-service
    
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /console
      