apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: service-discovery
spec:
  serviceName: "service-discovery"
  replicas: 3
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels: 
        app: service-discovery
    spec:
      containers:
      - name: service-discovery
        image: diegogomesaraujo/service-discovery
        ports:
        - containerPort: 8761
          name: http
        env:
        - name: DEFAULT_ZONE
          value: "http://service-discovery-0.service-discovery.default.svc.cluster.local:8761/eureka/,http://service-discovery-1.service-discovery.default.svc.cluster.local:8761/eureka/,http://service-discovery-2.service-discovery.default.svc.cluster.local:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  labels:
    app: service-discovery
spec:
  ports:
  - port: 8761
    name: http
  type: NodePort
  selector:
    app: service-discovery