
server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: ${GIR_REPO_URL}
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
            